package triggers

import (
	accountingtrigger "github.com/HiIamJeff67/notegic-backend/shared/platform/postgres/schemas/triggers/accounting_triggers"
	blockpackyjstrigger "github.com/HiIamJeff67/notegic-backend/shared/platform/postgres/schemas/triggers/block_pack_yjs_triggers"
	itemprojectiontrigger "github.com/HiIamJeff67/notegic-backend/shared/platform/postgres/schemas/triggers/item_projection_triggers"
	shelfitemcascadingtrigger "github.com/HiIamJeff67/notegic-backend/shared/platform/postgres/schemas/triggers/shelf_item_cascading_triggers"
)

var MigratingTriggerSQLs = []string{
	shelfitemcascadingtrigger.CascadingSoftDeleteRootShelfTriggerSQL,
	shelfitemcascadingtrigger.CascadingSoftDeleteSubShelfTriggerSQL,
	shelfitemcascadingtrigger.CascadingRestoreRootShelfTriggerSQL,
	shelfitemcascadingtrigger.CascadingRestoreSubShelfTriggerSQL,
	shelfitemcascadingtrigger.CascadingMoveSubShelfTriggerSQL,
	blockpackyjstrigger.SyncBlockPackYjsDocumentDeletedAtTriggerSQL,
	itemprojectiontrigger.ProjectSubShelvesToItemsTriggerSQL,
	itemprojectiontrigger.ProjectMaterialsToItemsTriggerSQL,
	itemprojectiontrigger.ProjectBlockPacksToItemsTriggerSQL,
	accountingtrigger.AccountingMutatedBlockPackTriggerSQL,
	accountingtrigger.AccountingInsertedBlockTriggerSQL,
	accountingtrigger.AccountingDeletedBlockTriggerSQL,
	accountingtrigger.AccountingMutatedRootShelfTriggerSQL,
	accountingtrigger.AccountingMutatedSubShelfTriggerSQL,
	accountingtrigger.AccountingMutatedMaterialTriggerSQL,
	accountingtrigger.AccountingInsertedRoutineTagTriggerSQL,
	accountingtrigger.AccountingDeletedRoutineTagTriggerSQL,
	accountingtrigger.AccountingInsertedRoutineTriggerSQL,
	accountingtrigger.AccountingDeletedRoutineTriggerSQL,
	accountingtrigger.AccountingInsertedStationTriggerSQL,
	accountingtrigger.AccountingDeletedStationTriggerSQL,
	accountingtrigger.AccountingMutatedStationTriggerSQL,
}

var RoutineTaskTriggerSQLs = []string{
	accountingtrigger.AccountingInsertedRoutineTaskTriggerSQL,
	accountingtrigger.AccountingDeletedRoutineTaskTriggerSQL,
	accountingtrigger.AccountingUpdatedRoutineTaskTriggerSQL,
}
