package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	cblockpacks "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/block-packs"
	cblocks "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/blocks"
	citems "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/items"
	cmaterials "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/materials"
	crootshelves "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/root-shelves"
	croutinetags "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/routine-tags"
	croutinetaskrecords "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/routine-task-records"
	croutinetasks "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/routine-tasks"
	croutines "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/routines"
	cstations "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/stations"
	csubshelves "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/sub-shelves"
	cthemes "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/themes"
	cusers "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/api/users"
	cgenerated "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/graphql/generated"
	cgqlmodels "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/graphql/models"
	gatewaycontexts "github.com/HiIamJeff67/notegic-backend/internal/clientgateway/contexts"
	coreadapters "github.com/HiIamJeff67/notegic-backend/internal/clientgateway/transports/core/adapters"
	sexceptionwriter "github.com/HiIamJeff67/notegic-backend/shared/util/exceptionwriter"
)

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, input cgqlmodels.SearchUserInput) (*cgqlmodels.SearchUserConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		cusers.SearchUsersRequestDto,
		cusers.SearchUsersResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		cusers.SearchUsersOperation,
		"/core/v1/users/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchThemes is the resolver for the searchThemes field.
func (r *queryResolver) SearchThemes(ctx context.Context, input cgqlmodels.SearchThemeInput) (*cgqlmodels.SearchThemeConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.Call[
		cthemes.SearchThemesRequestDto,
		cthemes.SearchThemesResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		cthemes.SearchThemesOperation,
		"/core/v1/themes/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRootShelves is the resolver for the searchRootShelves field.
func (r *queryResolver) SearchRootShelves(ctx context.Context, input cgqlmodels.SearchRootShelfInput) (*cgqlmodels.SearchRootShelfConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		crootshelves.SearchRootShelvesRequestDto,
		crootshelves.SearchRootShelvesResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		crootshelves.SearchRootShelvesOperation,
		"/core/v1/root-shelves/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchSubShelves is the resolver for the searchSubShelves field.
func (r *queryResolver) SearchSubShelves(ctx context.Context, input cgqlmodels.SearchSubShelfInput) (*cgqlmodels.SearchSubShelfConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		csubshelves.SearchSubShelvesRequestDto,
		csubshelves.SearchSubShelvesResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		csubshelves.SearchSubShelvesOperation,
		"/core/v1/sub-shelves/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchItems is the resolver for the searchItems field.
func (r *queryResolver) SearchItems(ctx context.Context, input cgqlmodels.SearchItemInput) (*cgqlmodels.SearchItemConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		citems.SearchItemsRequestDto,
		citems.SearchItemsResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		citems.SearchItemsOperation,
		"/core/v1/items/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchMaterials is the resolver for the searchMaterials field.
func (r *queryResolver) SearchMaterials(ctx context.Context, input cgqlmodels.SearchMaterialInput) (*cgqlmodels.SearchMaterialConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		cmaterials.SearchMaterialsRequestDto,
		cmaterials.SearchMaterialsResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		cmaterials.SearchMaterialsOperation,
		"/core/v1/materials/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchBlockPacks is the resolver for the searchBlockPacks field.
func (r *queryResolver) SearchBlockPacks(ctx context.Context, input cgqlmodels.SearchBlockPackInput) (*cgqlmodels.SearchBlockPackConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		cblockpacks.SearchBlockPacksRequestDto,
		cblockpacks.SearchBlockPacksResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		cblockpacks.SearchBlockPacksOperation,
		"/core/v1/block-packs/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchBlocks is the resolver for the searchBlocks field.
func (r *queryResolver) SearchBlocks(ctx context.Context, input cgqlmodels.SearchBlockInput) (*cgqlmodels.SearchBlockConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		cblocks.SearchBlocksRequestDto,
		cblocks.SearchBlocksResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		cblocks.SearchBlocksOperation,
		"/core/v1/blocks/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchStations is the resolver for the searchStations field.
func (r *queryResolver) SearchStations(ctx context.Context, input cgqlmodels.SearchStationInput) (*cgqlmodels.SearchStationConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		cstations.SearchStationsRequestDto,
		cstations.SearchStationsResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		cstations.SearchStationsOperation,
		"/core/v1/stations/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutines is the resolver for the searchRoutines field.
func (r *queryResolver) SearchRoutines(ctx context.Context, input cgqlmodels.SearchRoutineInput) (*cgqlmodels.SearchRoutineConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		croutines.SearchRoutinesRequestDto,
		croutines.SearchRoutinesResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		croutines.SearchRoutinesOperation,
		"/core/v1/routines/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutineTags is the resolver for the searchRoutineTags field.
func (r *queryResolver) SearchRoutineTags(ctx context.Context, input cgqlmodels.SearchRoutineTagInput) (*cgqlmodels.SearchRoutineTagConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		croutinetags.SearchRoutineTagsRequestDto,
		croutinetags.SearchRoutineTagsResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		croutinetags.SearchRoutineTagsOperation,
		"/core/v1/routine-tags/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutineTasks is the resolver for the searchRoutineTasks field.
func (r *queryResolver) SearchRoutineTasks(ctx context.Context, input cgqlmodels.SearchRoutineTaskInput) (*cgqlmodels.SearchRoutineTaskConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		croutinetasks.SearchRoutineTasksRequestDto,
		croutinetasks.SearchRoutineTasksResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		croutinetasks.SearchRoutineTasksOperation,
		"/core/v1/routine-tasks/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutineTaskRecords is the resolver for the searchRoutineTaskRecords field.
func (r *queryResolver) SearchRoutineTaskRecords(ctx context.Context, input cgqlmodels.SearchRoutineTaskRecordInput) (*cgqlmodels.SearchRoutineTaskRecordConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		croutinetaskrecords.SearchRoutineTaskRecordsRequestDto,
		croutinetaskrecords.SearchRoutineTaskRecordsResponseDto,
	](
		ginContext,
		r.coreAdapter,
		&input,
		croutinetaskrecords.SearchRoutineTaskRecordsOperation,
		"/core/v1/routine-task-records/graphql/search",
	)
	if exception != nil {
		return nil, sexceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// Query returns cgenerated.QueryResolver implementation.
func (r *Resolver) Query() cgenerated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
