package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	cgenerated "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/graphql/generated"
	cgqlmodels "github.com/HiIamJeff67/notegic-backend/contracts/core/v1/graphql/models"
)

// Info is the resolver for the info field.
func (r *publicUserResolver) Info(ctx context.Context, obj *cgqlmodels.PublicUser) (*cgqlmodels.PublicUserInfo, error) {
	return r.dataloader.UserInfoDataLoader.LoadByUserPublicId(ctx, obj.PublicID)
}

// PublicUser returns generated.PublicUserResolver implementation.
func (r *Resolver) PublicUser() cgenerated.PublicUserResolver { return &publicUserResolver{r} }

type publicUserResolver struct{ *Resolver }
